# Generated by Django 6.0 on 2026-03-28 13:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                ("topic", models.CharField(max_length=500)),
                ("simplified_topic", models.CharField(blank=True, max_length=300)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("simple", "Simple"), ("complex", "Complex")],
                        default="simple",
                        max_length=10,
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("num_questions", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "share_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_public", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quizsession_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answers", models.JSONField(default=dict)),
                ("bookmarks", models.JSONField(default=list)),
                ("flags", models.JSONField(default=list)),
                ("completed", models.BooleanField(default=False)),
                ("score", models.PositiveSmallIntegerField(default=0)),
                ("time_taken_seconds", models.PositiveIntegerField(default=0)),
                ("suggested_difficulty", models.CharField(blank=True, max_length=10)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quiz",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempt",
                        to="quiz.quizsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                ("question", models.TextField()),
                ("options", models.JSONField()),
                ("answer", models.TextField()),
                ("explanation", models.TextField()),
                ("topic", models.CharField(max_length=200)),
                ("difficulty_label", models.CharField(default="", max_length=20)),
                ("flag_count", models.PositiveSmallIntegerField(default=0)),
                ("is_hidden", models.BooleanField(default=False)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="quiz.quizsession",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("quiz", "order")},
            },
        ),
        migrations.CreateModel(
            name="QuestionFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("wrong_answer", "Wrong answer"),
                            ("bad_question", "Poorly worded"),
                            ("off_topic", "Off topic"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="quiz.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("question", "session_key"), ("question", "user")},
            },
        ),
    ]
